MCU = NRF52840

# Bootloader selection
BOOTLOADER = custom

# GCC ARM Toolchain path
GNU_INSTALL_ROOT =
GNU_PREFIX = arm-none-eabi

MOUSEKEY_ENABLE = yes
BOOTMAGIC_ENABLE = yes
# MIDI_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = IS31FL3741
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = pwm
# NRF_DEBUG = yes
DEBOUNCE_TYPE = sym_eager_pr
