
DEFAULT_FOLDER = pad_ble_new_oled/pro_v1

MCU = NRF52840

# GCC ARM Toolchain path
GNU_INSTALL_ROOT =
GNU_PREFIX = arm-none-eabi

MOUSEKEY_ENABLE = yes
BOOTMAGIC_ENABLE = full
# MIDI_ENABLE = yes
EXTRAKEY_ENABLE = yes
#NKRO_ENABLE = yes
# RGB_MATRIX_ENABLE = IS31FL3737
RGBLIGHT_ENABLE = yes
# NRF_DEBUG = yes
DEBOUNCE_TYPE = eager_pr
ENCODER_ENABLE = yes
OLED_DRIVER_ENABLE = yes
TAP_DANCE_ENABLE=yes
#CUSTOM_MATRIX = yes # This flag should be on for nrf52